<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telephantmaster.proto

namespace App\Protos\TelephantPointResult;

use UnexpectedValueException;

/**
 * Protobuf type <code>TelephantPointResult.PointOperator</code>
 */
class PointOperator
{
    /**
     * Generated from protobuf enum <code>PLUS = 0;</code>
     */
    const PLUS = 0;
    /**
     * Generated from protobuf enum <code>MINUS = 1;</code>
     */
    const MINUS = 1;

    private static $valueToName = [
        self::PLUS => 'PLUS',
        self::MINUS => 'MINUS',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(PointOperator::class, \App\Protos\TelephantPointResult_PointOperator::class);

