<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telephantmaster.proto

namespace App\Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>BapacParsedPoints</code>
 */
class BapacParsedPoints extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .BapacParsedPoint bapac_parsed_points = 1;</code>
     */
    private $bapac_parsed_points;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Protos\BapacParsedPoint[]|\Google\Protobuf\Internal\RepeatedField $bapac_parsed_points
     * }
     */
    public function __construct($data = NULL) {
        \App\Protos\GPBMetadata\Telephantmaster::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .BapacParsedPoint bapac_parsed_points = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBapacParsedPoints()
    {
        return $this->bapac_parsed_points;
    }

    /**
     * Generated from protobuf field <code>repeated .BapacParsedPoint bapac_parsed_points = 1;</code>
     * @param \App\Protos\BapacParsedPoint[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBapacParsedPoints($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Protos\BapacParsedPoint::class);
        $this->bapac_parsed_points = $arr;

        return $this;
    }

}

