<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telephantmaster.proto

namespace App\Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>BapacParsedPoint</code>
 */
class BapacParsedPoint extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .TelephantBapac bapac = 1;</code>
     */
    protected $bapac = null;
    /**
     * Generated from protobuf field <code>optional int64 parsed_points = 2;</code>
     */
    protected $parsed_points = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Protos\TelephantBapac $bapac
     *     @type int|string $parsed_points
     * }
     */
    public function __construct($data = NULL) {
        \App\Protos\GPBMetadata\Telephantmaster::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .TelephantBapac bapac = 1;</code>
     * @return \App\Protos\TelephantBapac|null
     */
    public function getBapac()
    {
        return $this->bapac;
    }

    public function hasBapac()
    {
        return isset($this->bapac);
    }

    public function clearBapac()
    {
        unset($this->bapac);
    }

    /**
     * Generated from protobuf field <code>optional .TelephantBapac bapac = 1;</code>
     * @param \App\Protos\TelephantBapac $var
     * @return $this
     */
    public function setBapac($var)
    {
        GPBUtil::checkMessage($var, \App\Protos\TelephantBapac::class);
        $this->bapac = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int64 parsed_points = 2;</code>
     * @return int|string
     */
    public function getParsedPoints()
    {
        return isset($this->parsed_points) ? $this->parsed_points : 0;
    }

    public function hasParsedPoints()
    {
        return isset($this->parsed_points);
    }

    public function clearParsedPoints()
    {
        unset($this->parsed_points);
    }

    /**
     * Generated from protobuf field <code>optional int64 parsed_points = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setParsedPoints($var)
    {
        GPBUtil::checkInt64($var);
        $this->parsed_points = $var;

        return $this;
    }

}

