<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telephantmaster.proto

namespace App\Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TelephantPointResult</code>
 */
class TelephantPointResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional int64 user_id = 1;</code>
     */
    protected $user_id = null;
    /**
     * Generated from protobuf field <code>optional string key = 2;</code>
     */
    protected $key = null;
    /**
     * Generated from protobuf field <code>optional .TelephantPointResult.PointOperator op = 3;</code>
     */
    protected $op = null;
    /**
     * Generated from protobuf field <code>optional int32 count = 4;</code>
     */
    protected $count = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $user_id
     *     @type string $key
     *     @type int $op
     *     @type int $count
     * }
     */
    public function __construct($data = NULL) {
        \App\Protos\GPBMetadata\Telephantmaster::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional int64 user_id = 1;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return isset($this->user_id) ? $this->user_id : 0;
    }

    public function hasUserId()
    {
        return isset($this->user_id);
    }

    public function clearUserId()
    {
        unset($this->user_id);
    }

    /**
     * Generated from protobuf field <code>optional int64 user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string key = 2;</code>
     * @return string
     */
    public function getKey()
    {
        return isset($this->key) ? $this->key : '';
    }

    public function hasKey()
    {
        return isset($this->key);
    }

    public function clearKey()
    {
        unset($this->key);
    }

    /**
     * Generated from protobuf field <code>optional string key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .TelephantPointResult.PointOperator op = 3;</code>
     * @return int
     */
    public function getOp()
    {
        return isset($this->op) ? $this->op : 0;
    }

    public function hasOp()
    {
        return isset($this->op);
    }

    public function clearOp()
    {
        unset($this->op);
    }

    /**
     * Generated from protobuf field <code>optional .TelephantPointResult.PointOperator op = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOp($var)
    {
        GPBUtil::checkEnum($var, \App\Protos\TelephantPointResult\PointOperator::class);
        $this->op = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 count = 4;</code>
     * @return int
     */
    public function getCount()
    {
        return isset($this->count) ? $this->count : 0;
    }

    public function hasCount()
    {
        return isset($this->count);
    }

    public function clearCount()
    {
        unset($this->count);
    }

    /**
     * Generated from protobuf field <code>optional int32 count = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->count = $var;

        return $this;
    }

}

