<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telephantmaster.proto

namespace App\Protos;

if (false) {
    /**
     * This class is deprecated. Use App\Protos\TelephantPointResult\PointOperator instead.
     * @deprecated
     */
    class TelephantPointResult_PointOperator {}
}
class_exists(TelephantPointResult\PointOperator::class);
@trigger_error('App\Protos\TelephantPointResult_PointOperator is deprecated and will be removed in the next major release. Use App\Protos\TelephantPointResult\PointOperator instead', E_USER_DEPRECATED);

