<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telephantmaster.proto

namespace App\Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TelephantBapac</code>
 */
class TelephantBapac extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional uint64 id = 3;</code>
     */
    protected $id = null;
    /**
     * Generated from protobuf field <code>optional string first_name = 1;</code>
     */
    protected $first_name = null;
    /**
     * Generated from protobuf field <code>optional string last_name = 2;</code>
     */
    protected $last_name = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $first_name
     *     @type string $last_name
     * }
     */
    public function __construct($data = NULL) {
        \App\Protos\GPBMetadata\Telephantmaster::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint64 id = 3;</code>
     * @return int|string
     */
    public function getId()
    {
        return isset($this->id) ? $this->id : 0;
    }

    public function hasId()
    {
        return isset($this->id);
    }

    public function clearId()
    {
        unset($this->id);
    }

    /**
     * Generated from protobuf field <code>optional uint64 id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string first_name = 1;</code>
     * @return string
     */
    public function getFirstName()
    {
        return isset($this->first_name) ? $this->first_name : '';
    }

    public function hasFirstName()
    {
        return isset($this->first_name);
    }

    public function clearFirstName()
    {
        unset($this->first_name);
    }

    /**
     * Generated from protobuf field <code>optional string first_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFirstName($var)
    {
        GPBUtil::checkString($var, True);
        $this->first_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string last_name = 2;</code>
     * @return string
     */
    public function getLastName()
    {
        return isset($this->last_name) ? $this->last_name : '';
    }

    public function hasLastName()
    {
        return isset($this->last_name);
    }

    public function clearLastName()
    {
        unset($this->last_name);
    }

    /**
     * Generated from protobuf field <code>optional string last_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLastName($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_name = $var;

        return $this;
    }

}

